apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: alb
    # Decides who can reach your app.
    #Internet facing means public internet can hit it.
    alb.ingress.kubernetes.io/scheme: internet-facing
    
    #Targets pods directly using their IPs.
    #Better for Kubernetes, fewer hops, works nicely with managed node groups and Fargate.
    alb.ingress.kubernetes.io/target-type: ip
    
    # Says the ALB must listen on port 443 with HTTPS.
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]' 

    # Forces every HTTP request to redirect to HTTPS.
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/backend-protocol: HTTPS

    # Specifies the ARN of the ACM certificate to use for HTTPS. 
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:864899854951:certificate/c68e0064-c17e-472a-ada3-9598ef6c4219
    
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-path: /healthz

spec:
  # defines which IngressClass to use,
  # in this case the AWS ALB Ingress Controller
  ingressClassName: alb
  rules:
    - host: argocd.vishukumarpatel.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                # name of the service to route traffic to
                # must be in the same namespace as the Ingress
                # for this example, the "argocd-server" service
                name: argocd-server
                port:
                  number: 443