---
# Source: opentelemetry-demo/templates/component.yaml
apiVersion: apps/v1
kind: Deployment # Defines a Deployment type resource
metadata: # Metadata for the Deployment type resource
  name: opentelemetry-demo-recommendationservice
  labels:
    # labels used for organization and selection
    # these labels are for identifying the application and its version
    # they don't use in service discovery   
    opentelemetry.io/name: opentelemetry-demo-recommendationservice
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/component: recommendationservice
    app.kubernetes.io/name: opentelemetry-demo-recommendationservice
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: opentelemetry-demo
# Here we define the specification of the Deployment
# This includes the number of replicas, the selector for pods,
# and the template for the pods
spec:
  replicas: 1 # Number of pod replicas to run
  revisionHistoryLimit: 10 # Number of old ReplicaSets to retain
  # Selector to identify the pods managed by this Deployment
  # This must match the labels defined in the pod template
  selector:
    matchLabels:
      opentelemetry.io/name: opentelemetry-demo-recommendationservice
  # Template for the pods managed by this Deployment
  template:
    metadata:
      # This labels must match the selector above
      labels:
        opentelemetry.io/name: opentelemetry-demo-recommendationservice
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/component: recommendationservice
        app.kubernetes.io/name: opentelemetry-demo-recommendationservice
    # Specification of the pod
    spec:
      serviceAccountName: opentelemetry-demo
      containers:
        - name: recommendationservice
          image: imv27/devops-otel-recommendation:20684066398
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # Port on which the container listens
              name: service
          # Environment variables for the container
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: 'opentelemetry-demo-otelcol'
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: RECOMMENDATION_SERVICE_PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: 'opentelemetry-demo-productcatalogservice:8080'
            - name: PRODUCT_CATALOG_ADDR
              value: 'opentelemetry-demo-productcatalogservice:8080'
            - name: OTEL_PYTHON_LOG_CORRELATION
              value: "true"
            - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
              value: python
            - name: FLAGD_HOST
              value: 'opentelemetry-demo-flagd'
            - name: FLAGD_PORT
              value: "8013"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_COLLECTOR_NAME):4317
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
          resources:
            limits:
              memory: 500Mi
          volumeMounts:
      volumes:
